import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AddToCart } from '@/components/add-to-cart';
import { getProduct, getProducts } from '@/lib/products';
import { ApiError } from '@/lib/api';
export async function generateStaticParams() { try { return (await getProducts()).map(product=>({id:String(product.id)})); } catch { return []; } }
export async function generateMetadata({params}:{params:{id:string}}):Promise<Metadata>{try{const p=await getProduct(params.id);return{title:p.title,description:p.description,openGraph:{title:p.title,description:p.description,images:[p.image]}}}catch{return{title:'Piece not found'}}}
export default async function ProductPage({params}:{params:{id:string}}){let product;try{product=await getProduct(params.id)}catch(error){if(error instanceof ApiError&&error.status===404)notFound();throw error}if(!product||!Number.isFinite(product.id))notFound();const jsonLd={"@context":"https://schema.org","@type":"Product",name:product.title,image:product.image,description:product.description,category:product.category,sku:String(product.id),offers:{"@type":"Offer",priceCurrency:"USD",price:product.price.toFixed(2),availability:"https://schema.org/InStock"},aggregateRating:{"@type":"AggregateRating",ratingValue:product.rating.rate,reviewCount:product.rating.count}};return <div className="page-shell detail-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><nav className="breadcrumbs"><Link href="/products">Products</Link><span>/</span><span>{product.category}</span></nav><div className="detail-layout"><div className="detail-image"><Image src={product.image} alt={product.title} fill sizes="(max-width: 800px) 100vw, 55vw" priority/></div><div className="detail-info"><span className="eyebrow detail-category">{product.category}</span><h1>{product.title}</h1><div className="detail-rating"><span>★ ★ ★ ★ ★</span><b>{product.rating.rate}</b><span>({product.rating.count} reviews)</span></div><p className="detail-price">${product.price.toFixed(2)}</p><p className="detail-description">{product.description}</p><AddToCart product={product}/></div></div></div>}
